name: Update README with recent activity

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          GH_USERNAME: godaralokesh29   # 👈 your GitHub username
          MAX_LINES: 4
